---
title: "An Analysis of Random Forest"
author: "Jessica Cramer, Hunter Hillis, Murpys D. Mendez"
date: 2025-10-25
format:
   revealjs:
    theme: simple
    scrollable: true
    smaller: true
    margin: 0.01
    auto-stretch: false
    width: 1200
    height: 900
    max-scale: 1.5
    view-distance: 30
    mobile-view-distance: 30
    css: styles.css
editor: source
course: IDC 69407 - Capstone Projects in Data Science
bibliography: references.bib # file contains bibtex for references
link-citations: true
self-contained: true
execute: 
  warning: false
  message: false
---

## This is the begining of a slide



## Method

<p>&nbsp;</p>

- Random Forests is an ensemble method that combines many decision trees
<p>&nbsp;</p>
- Each tree is built on a different randomization (bootstrap sampling + random features)
<p>&nbsp;</p>
- Bootstrap sampling is creates new samples by randomly drawing with replacement
<p>&nbsp;</p>
- Trees are grown until all terminal nodes (leaves) are pure or another stopping criterion is met
<p>&nbsp;</p>
- A result is reached by aggregating the predictions of the individual trees
<p>&nbsp;</p>
- Classification: majority vote of the trees (mode)
<p>&nbsp;</p>
- Regression: average of the tree predictions

## Splitting criteria

<p>&nbsp;</p>

At every node a random subset of features is chosen, and the best split is selected

<p>&nbsp;</p>

- Gini index(classification) $$i_G(t) = 1 - \sum_{k=1}^{J} p(c_k \mid t)^2$$


- Entropy(classification) $$i_H(t) = - \sum_{k=1}^{J} p(c_k \mid t) \, \log_2 \big( p(c_k \mid t) \big)$$


- Mean Squared Error(regression) $$\text{MSE} = \frac{1}{N} \sum_{i=1}^{N} (y_i - \hat{y}_i)^2$$


## Hyperparameters

<p>&nbsp;</p>

Hyperparameter tuning balances model complexity, computation, and generalization

<p>&nbsp;</p>

***Commonly tuned parameters***
<p>&nbsp;</p>

- *ntree*: number of trees
<p>&nbsp;</p>
- *maxnodes*: maximum depth of each tree
<p>&nbsp;</p>
- *mtry*: number of features considered at each split
<p>&nbsp;</p>
- *nodesize*: controls the minimum number of observations a terminal node (leaf) must have







## This is the begining of a slide



## This is the begining of a slide



## References